export let cardsDeck = [
    'ace-clubs.jpg',
    'ace-diamonds.jpg',
    'ace-hearts.jpg',
    'ace-spade.png',
    'deuce-diamonds.jpg',
    'deuce-hearts.jpg',
    'deuce-spade.jpg',
    'deuce-clubs.jpg',
    'eight-diamonds.jpg',
    'eight-hearts.jpg',
    'eight-spade.jpg',
    'eight-clubs.jpg',
    'five-diamonds.jpg',
    'five-hearts.jpg',
    'five-spade.jpg',
    'five-clubs.jpg',
    'for-diamonds.jpg',
    'for-hearts.jpg',
    'for-spade.jpg',
    'for-clubs.jpg',
    'jack-diamonds.jpg',
    'jack-hearts.jpg',
    'jack-spade.jpg',
    'jack-clubs.jpg',
    'king-diamonds.jpg',
    'king-hearts.jpg',
    'king-spade.jpg',
    'king-clubs.jpg',
    'nine-diamonds.jpg',
    'nine-hearts.jpg',
    'nine-spade.jpg',
    'nine-clubs.jpg',
    'queen-diamonds.jpg',
    'queen-hearts.jpg',
    'queen-spade.jpg',
    'queen-clubs.jpg',
    'seven-diamonds.jpg',
    'seven-hearts.jpg',
    'seven-spade.jpg',
    'seven-clubs.jpg',
    'six-diamonds.jpg',
    'six-hearts.jpg',
    'six-spade.jpg',
    'six-clubs.jpg',
    'ten-diamonds.jpg',
    'ten-hearts.jpg',
    'ten-spade.jpg',
    'ten-clubs.jpg',
    'three-diamonds.jpg',
    'three-hearts.jpg',
    'three-spade.jpg',
    'three-clubs.jpg',
];

export let cardsForDouble = {
   "deuce" : 2,
   "three": 3,
   "for": 4,
   "five": 5,
   "six": 6,
   "seven": 7,
   "eight": 8,
   "nine": 9,
   "ten": 10,
   "jack": 11,
   "queen": 12,
   "king": 13,
   "ace": 15
};

